version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: atlas_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_schema
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d