services:
  db:
    image: mysql:8.0
    container_name: atlas_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_schema
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:16-alpine
    container_name: atlas_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: test_schema
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: